sonar.projectKey=noxed
sonar.projectName=noxed

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/__tests__/**/*.test.ts
sonar.exclusions=src/**/__tests__/**/*.test.ts,src/preload/index.d.ts

sonar.sourceEncoding=UTF-8
