sonar.projectKey=noxed
sonar.projectName=noxed

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/__tests__/**/*.test.ts,src/**/__tests__/**/*.test.tsx
sonar.exclusions=src/**/__tests__/**,src/preload/index.d.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
